spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://mysql-container:3306/coffee'
    username: root
    password: root

  sql:
    init:
      mode: always
      schema-locations: 'classpath:/data/schema.sql'
      data-locations: 'classpath:/data/data.sql'
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false




